---

- hosts: "{{host}}"
  vars:
    - test_root: "/var/lib/zstack/testagent"
    - chroot_env: "{{chroot|default('false')}}"

  tasks:
    - name: create root directories
      shell: "mkdir -p {{item}}"
      with_items:
        - "{{test_root}}"

    - name: disable firewalld in RHEL7 and Centos7
      when: ansible_os_family == 'RedHat' and ansible_distribution_version >= '7'
      service: name=firewalld state=stopped enabled=no

    - name: copy test agent
      copy: src="{{testagentdir}}/target/testagent" dest="{{test_root}}/"

    - name: copy test agent service file
      copy: src="{{testagentdir}}/scripts/zstack-testagent" dest="/etc/init.d/" mode=755
      notify:
        - restart testagent

    - meta: flush_handlers

    - name: enable testagent service 1
      service: name=zstack-testagent enabled=yes state=started
      when: chroot_env == 'false'

    - name: enable testagent service 2
      service: name=zstack-testagent enabled=yes
      when: chroot_env == 'true'

    - name: enable iptables 9393 port
      shell: "iptables-save|grep 9393 || iptables -I INPUT -p tcp -m tcp --dport 9393 -j ACCEPT"
      when: chroot_env == 'false'

  handlers:
    - name: restart testagent
      service: name=zstack-testagent state=restarted enabled=yes
      when: chroot_env == 'false'

